version: "3"

services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    environment:
      - DATABASE_HOSTNAME=localhost
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=postgres
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=ajfbakfnsadfasfneufb8vwqtqichwqehqw
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres:15.3-alpine3.18
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=grocery_store_db
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: